# Generated by Django 5.2 on 2025-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr", "0002_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="knownface",
            name="password",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
